/gps/particle opticalphoton
#/gps/energy 2.01 eV #Low energy photon
/gps/energy 2.95 eV #blue photon
#/gps/energy 12 eV


/gps/position 0 0 0 cm # Center of cell
#/gps/position 0 0.625 0 cm # In TPB layer
#/gps/position 0 0.650 0 cm # Just above cell


#/gps/ang/type beam1d
/gps/ang/type iso
#/gps/direction 0 -1 0
#/gps/direction 1 0 0
/gps/polarization 0 0 1 # dummy polarization


/run/beamOn 10000