/vis/modeling/trajectories/create/drawByAttribute
/vis/modeling/trajectories/drawByAttribute-0/setAttribute IKE
/vis/scene/notifyHandlers scene-0
#/vis/scene/notifyHandlers scene-1
/vis/modeling/trajectories/drawByAttribute-0/addInterval interval1 0.0 eV 2.8 eV
/vis/scene/notifyHandlers scene-0
#/vis/scene/notifyHandlers scene-1
/vis/modeling/trajectories/drawByAttribute-0/addInterval interval2 2.8 eV 10.0 eV
/vis/scene/notifyHandlers scene-0
#/vis/scene/notifyHandlers scene-1
/vis/modeling/trajectories/drawByAttribute-0/interval1/setLineColour green
/vis/scene/notifyHandlers scene-0
#/vis/scene/notifyHandlers scene-1
/vis/modeling/trajectories/drawByAttribute-0/interval2/setLineColour blue
/vis/scene/notifyHandlers scene-0
#/vis/scene/notifyHandlers scene-1
